First Working version with TimescaleDB Toolkit

diff --git a/timescaledb/Dockerfile b/timescaledb/Dockerfile
--- a/timescaledb/Dockerfile
+++ b/timescaledb/Dockerfile
@@ -1,4 +1,4 @@
-ARG BUILD_FROM=ghcr.io/hassio-addons/base/aarch64:14.0.2
+ARG BUILD_FROM=ghcr.io/hassio-addons/base/aarch64:15.0.6
 ARG BUILD_ARCH=aarch64
 ARG GO_VERSION=1.19.0
 
@@ -7,15 +7,8 @@ ARG GO_VERSION=1.19.0
 ###########################################
 FROM $BUILD_FROM as addon-base
 
-RUN sed -i "s/libcrypto3=3.1.1-r1/libcrypto3=3.1.1-r2/g" /etc/apk/world \
-    && sed -i "s/libssl3=3.1.1-r1/libssl3=3.1.1-r2/g" /etc/apk/world \
-    && apk update \
-    && apk upgrade
-
-####################################
-# Previous Addon Image
-####################################
-FROM husselhans/hassos-addon-timescaledb-${BUILD_ARCH}:2.1.1 as previous-addon
+RUN --mount=type=cache,id=apk-${TARGETARCH}-${TARGETVARIANT},sharing=locked,target=/var/cache/apk \
+    apk update
 
 ###########################################
 # Build TimeScaleDB-tools
@@ -37,97 +30,61 @@ FROM addon-base as addon
 ARG BUILD_ARCH
 
 # Add some build-tools
-RUN apk add --no-cache --virtual .build-tools \
+RUN --mount=type=cache,id=apk-${TARGETARCH}-${TARGETVARIANT},sharing=locked,target=/var/cache/apk \
+    apk add --virtual .build-tools \
     wget \
     rsync
 
 # -----------------------------------------
-# PostgreSql 14
+# Install postgreSql 15 (OLD)
 # -----------------------------------------
-
-# Add Postgresql 14
-RUN apk add --no-cache \
-    postgresql14-jit \
-    postgresql14 \
-    postgresql14-dev \
-    postgresql14-contrib-jit \
-    postgresql14-contrib
-
-
-# Make sure pg_config follows the most current version
-RUN rm /usr/bin/pg_config \
-    && ln -s /usr/libexec/postgresql/pg_config /usr/bin/pg_config
-
-
-# --------------------------------------
-# TimescaleDB for PostgreSQl 14 - Build and install
-# --------------------------------------
-# Enable this if you only want the OSS parts
-#ENV OSS_ONLY -DAPACHE_ONLY=1
-ARG TIMESCALEDB_VERSION=2.11.1
-RUN set -ex \
-    && apk add --no-cache --virtual .fetch-deps \
-                ca-certificates \
-                git \
-                openssl \
-                openssl-dev \
-                tar \
-    && mkdir -p /build/ \
-    && git clone https://github.com/timescale/timescaledb /build/timescaledb \
-    \
-    && apk add --no-cache -u musl \
-    && apk add --no-cache --virtual .build-deps \
-                coreutils \
-                dpkg-dev dpkg \
-                gcc \
-                krb5-dev \
-                libc-dev \
-                make \
-                cmake \
-                util-linux-dev \
-    \
-    # Build current version
-    && cd /build/timescaledb && rm -fr build \
-    && git checkout ${TIMESCALEDB_VERSION} \
-    && ./bootstrap -DCMAKE_BUILD_TYPE=RelWithDebInfo -DREGRESS_CHECKS=OFF -DTAP_CHECKS=OFF -DGENERATE_DOWNGRADE_SCRIPT=ON -DWARNINGS_AS_ERRORS=OFF -DPROJECT_INSTALL_METHOD="docker"${OSS_ONLY} \
-    # BUGFIX Line below is used to fix the error that <postgres.h> cannot be found, even though we have the postgres-dev package installed.
-    && export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/include/postgresql/14/server \
-    && cd build && make install \
-    && cd ~ \
-    \
-    && if [ "${OSS_ONLY}" != "" ]; then rm -f $(pg_config --pkglibdir)/timescaledb-tsl-*.so; fi \
-    && rm -rf /build 
-
-# -----------------------------------------
-# PostgreSql 15
-# -----------------------------------------
-
-#Add Postgresql 15
-RUN apk add --no-cache \
+RUN --mount=type=cache,id=apk-${TARGETARCH}-${TARGETVARIANT},sharing=locked,target=/var/cache/apk \
+    apk add \
     postgresql15-jit \
     postgresql15 \
     postgresql15-dev \
     postgresql15-contrib-jit \
     postgresql15-contrib
 
+# Make sure pg_config follows the most current version
+RUN rm /usr/bin/pg_config \
+    && ln -s /usr/libexec/postgresql/pg_config /usr/bin/pg_config
 
-# Set default postgresql version
+
+# -----------------------------------------
+# PostgreSql 16 (NEW)
+# -----------------------------------------
+
+RUN --mount=type=cache,id=apk-${TARGETARCH}-${TARGETVARIANT},sharing=locked,target=/var/cache/apk \
+    apk add \
+    postgresql16-jit \
+    postgresql16 \
+    postgresql16-dev \
+    postgresql16-contrib-jit \
+    postgresql16-contrib
+
+
+# Set default postgresql version to 16
 RUN rm /usr/libexec/postgresql \
-    && ln -s /usr/libexec/postgresql15 /usr/libexec/postgresql \
+    && ln -s /usr/libexec/postgresql16 /usr/libexec/postgresql \
     && rm /usr/share/postgresql \
-    && ln -s /usr/share/postgresql15 /usr/share/postgresql
+    && ln -s /usr/share/postgresql16 /usr/share/postgresql
 
 # Add JIT support
-RUN apk add --no-cache \
-	-u llvm14-libs
+#RUN apk add --no-cache \
+#	-u llvm14-libs
 
-# Add LatestTimescaleDB and Postgis
-RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ \
-        postgis=3.3.3-r1 \
+# Add Latest Postgis
+RUN --mount=type=cache,id=apk-${TARGETARCH}-${TARGETVARIANT},sharing=locked,target=/var/cache/apk \
+    apk add --repository https://dl-cdn.alpinelinux.org/alpine/v3.19/community \
+        postgis=3.4.2-r0 \
         gdal-driver-PostGISRaster \
     && \
-    apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ \
+    apk add --repository https://dl-cdn.alpinelinux.org/alpine/v3.19/main \
         libturbojpeg
+#    && \
+#    apk add --repository https://dl-cdn.alpinelinux.org/alpine/edge/community \
+#        postgresql-timescaledb=2.13.1-r0
 
 # Create it's run directory
 RUN mkdir -p /run/postgresql \
@@ -135,59 +92,23 @@ RUN mkdir -p /run/postgresql \
     && mkdir -p /run/postgresql/extensions \
 	&& chown -R postgres:postgres /run/postgresql/extensions
 
-# --------------------------------------
-# TimescaleDB for PostgreSQl 15 - Build and install
-# --------------------------------------
-# Enable this if you only want the OSS parts
-RUN set -ex \
-    && apk add --no-cache --virtual .fetch-deps \
-                ca-certificates \
-                git \
-                openssl \
-                openssl-dev \
-                tar \
-    && mkdir -p /build/ \
-    && git clone https://github.com/timescale/timescaledb /build/timescaledb \
-    \
-    && apk add --no-cache -u musl \
-    && apk add --no-cache --virtual .build-deps \
-                coreutils \
-                dpkg-dev dpkg \
-                gcc \
-                krb5-dev \
-                libc-dev \
-                make \
-                cmake \
-                util-linux-dev \
-    \
-    # Build current version
-    && cd /build/timescaledb && rm -fr build \
-    && git checkout ${TIMESCALEDB_VERSION} \
-    && ./bootstrap -DCMAKE_BUILD_TYPE=RelWithDebInfo -DREGRESS_CHECKS=OFF -DTAP_CHECKS=OFF -DGENERATE_DOWNGRADE_SCRIPT=ON -DWARNINGS_AS_ERRORS=OFF -DPROJECT_INSTALL_METHOD="docker"${OSS_ONLY} \
-    # BUGFIX Line below is used to fix the error that <postgres.h> cannot be found, even though we have the postgres-dev package installed.
-    && export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/include/postgresql/15/server \
-    && cd build && make install \
-    && cd ~ \
-    \
-    && if [ "${OSS_ONLY}" != "" ]; then rm -f $(pg_config --pkglibdir)/timescaledb-tsl-*.so; fi \
-    && apk del .fetch-deps .build-deps \
-    && rm -rf /build 
 
 # --------------------------------------------
-# pgAgent - build and install
+# pgAgent - build pached version and install
 # --------------------------------------------
 RUN mkdir -p /build
 COPY pgagent.patch /build/
 
-RUN set -ex \
-    && apk add --no-cache --virtual .fetch-deps \
+RUN --mount=type=cache,id=apk-${TARGETARCH}-${TARGETVARIANT},sharing=locked,target=/var/cache/apk \
+    set -ex \
+    && apk add --virtual .fetch-deps \
                 ca-certificates \
                 git \
                 openssl \
                 openssl-dev \
                 tar \
-    && apk add --no-cache -u musl \
-    && apk add --no-cache --virtual .build-deps \
+        && apk add -u musl \
+    && apk add --virtual .build-deps \
                 coreutils \
                 gcc \
                 make \
@@ -195,17 +116,76 @@ RUN set -ex \
 				build-base \
 				boost-dev \
 				openldap-dev \
-    && git clone https://github.com/postgres/pgagent /build/pgagent \
+&& git clone https://github.com/postgres/pgagent /build/pgagent \
     && cd /build/pgagent \
     && git checkout ${pgagent_version} \
-    && git apply -v ../pgagent.patch \
+&& git apply -v ../pgagent.patch \
     && cmake . \
     && make && make install \
     && cd ~ \
     && apk del .fetch-deps .build-deps \
     && rm -rf /build \
-	&& apk add --no-cache \
+	&& apk add \
 				boost-libs
+
+# --------------------------------------
+# PostGIS - Add required packages for runtime (see postgis dependencies)
+# --------------------------------------
+RUN --mount=type=cache,id=apk-${TARGETARCH}-${TARGETVARIANT},sharing=locked,target=/var/cache/apk \
+    set -ex \
+    && apk add  \
+	openexr \ 
+    poppler \
+    gdal \
+    geos \
+    json-c \
+    libgcc \
+    libpq \
+    libstdc++ \
+    libxml2 \ 
+    musl \
+    pcre \
+    perl \
+    proj \
+    protobuf-c
+
+# --------------------------------------
+# PostGIS - Build and install OLD Postgis (for upgrade reasons)
+# --------------------------------------
+ENV POSTGIS_VERSION 3.3.3
+RUN --mount=type=cache,id=apk-${TARGETARCH}-${TARGETVARIANT},sharing=locked,target=/var/cache/apk \
+    set -ex \
+    && apk add --virtual .fetch-deps \
+                ca-certificates \
+                git \
+                openssl \
+                openssl-dev \
+                tar \
+                wget \
+    && mkdir -p /build/ \
+    && wget -P /build https://download.osgeo.org/postgis/source/postgis-${POSTGIS_VERSION}.tar.gz \
+    && apk add --virtual .build-deps \
+                coreutils \
+                gcc \
+                make \
+                cmake \
+				build-base \
+                libxml2-dev \
+                protobuf-c-dev \
+    #&& apk add --virtual .community-build-deps --repository http://dl-cdn.alpinelinux.org/alpine/v3.17/community/ \
+    && apk add --virtual .community-build-deps \
+                geos-dev \
+                proj-dev \
+                gdal-dev \
+    && cd /build \
+    && tar xvzf postgis-${POSTGIS_VERSION}.tar.gz \
+    && cd /build/postgis-${POSTGIS_VERSION} \
+    && ./configure --with-pgconfig=/usr/libexec/postgresql15/pg_config \
+    && make && make install \
+    && cd ~ \
+    && apk del .fetch-deps .build-deps .community-build-deps \
+    && rm -rf /build 
+
 
 ###########################################
 # Timescaledb toolkit - Build and Install
@@ -216,6 +196,60 @@ RUN set -ex \
 # https://stackoverflow.com/questions/57749127/how-can-i-specify-the-glibc-version-in-cargo-build-for-rust
 # https://stackoverflow.com/questions/57749127/how-can-i-specify-the-glibc-version-in-cargo-build-for-rust
 
+# --------------------------------------
+# Timescaledb toolkit - Build and Install
+# --------------------------------------
+FROM addon AS timescaledb-toolkit
+ENV ALPINE_VERSION 3.19
+ENV TOOLKIT_VERSION 1.18.0
+RUN --mount=type=cache,id=apk-${TARGETARCH}-${TARGETVARIANT},sharing=locked,target=/var/cache/apk \
+    set -ex \
+    && apk add --virtual .fetch-deps \
+                ca-certificates \
+                git \
+                openssl \
+                openssl-dev \
+                tar \
+                wget \
+                curl \
+    && apk add --virtual .build-deps \
+                coreutils \
+                gcc \
+                make \
+                cmake \
+		        build-base \
+                gcompat \
+    #&& apk add --virtual .community-build-deps --repository http://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}/community/ \
+    && apk add --virtual .community-build-deps \
+                rust \
+                cargo \
+    && export PATH="/root/.cargo/bin:${PATH}" \
+    && cargo install cargo-pgx --version '^0.2'\
+    && cargo install rustfmt
+
+RUN set -ex \
+    && mkdir -p /build/ \
+    # && chown postgres:postgres -R /build \
+    # && chown postgres:postgres -R /usr/share/postgresql14 \
+    # && chown postgres:postgres -R /usr/lib/postgresql14 \        
+    && cd /build \
+        && git clone https://github.com/timescale/timescaledb-toolkit.git . \
+        && git checkout ${TOOLKIT_VERSION} \
+        && cd extension \
+        # initdb fails as root so generate the correct config ourselves
+        # && cargo pgx init --pg16 /usr/lib/postgresql/14/bin/pg_config        
+        && mkdir -p /root/.pgx \
+        && printf '[configs]\npg14="/usr/libexec/postgresql16/pg_config"\n' > /root/.pgx/config.toml \
+        && cargo pgx install --release --pg_config /usr/libexec/postgresql16/pg_config \
+        && cargo run --manifest-path ../tools/post-install/Cargo.toml -- /usr/libexec/postgresql16/pg_config \
+    && cd ~ \
+    && apk del .fetch-deps .build-deps .community-build-deps \
+    && rm -rf /build
+
+#Define timesaledb versions
+FROM timescale/timescaledb:2.14.1-pg15 as timescale-pg15
+FROM timescale/timescaledb:2.14.1-pg16 as timescale-pg16
+
 FROM addon
 
 # Copy timescaledb-toolkit
@@ -225,16 +259,23 @@ FROM addon
 # Copy timescaledb-tools
 COPY --from=timescaledb-tools /go/bin/* /usr/local/bin/
 
-# Copy the timescaledb and postgis extensions from the previous addon
-COPY --from=previous-addon /usr/lib/postgresql14/timescale* /usr/lib/postgresql14/
-COPY --from=previous-addon /usr/lib/postgresql14/postgis* /usr/lib/postgresql14/
-COPY --from=previous-addon /lib/libssl.so.1.1 /lib/
-COPY --from=previous-addon /lib/libcrypto.so.1.1 /lib/
+# Copy all timescale newversions to the old postgresql version
+COPY --from=timescale-pg15 /usr/local/lib/postgresql/timescaledb*.so /usr/lib/postgresql15/
+COPY --from=timescale-pg15 /usr/local/share/postgresql/extension/timescaledb* /usr/share/postgresql15/extension/
 
-# Add nano for debugging
-# RUN set -ex \
-#     && apk add --no-cache \
-#     nano
+# Copy all timescale newversions to the old postgresql version
+COPY --from=timescale-pg16 /usr/local/lib/postgresql/timescaledb*.so /usr/lib/postgresql16/
+COPY --from=timescale-pg16 /usr/local/share/postgresql/extension/timescaledb* /usr/share/postgresql16/extension/
+
+# Copy libssl over from the old addon. This version is needed in alpine 3.19]
+COPY --from=timescale-pg15 /lib/libssl.so.1.1 /lib/
+COPY --from=timescale-pg15 /lib/libcrypto.so.1.1 /lib/
+
+#Add nano for debugging
+RUN --mount=type=cache,id=apk-${TARGETARCH}-${TARGETVARIANT},sharing=locked,target=/var/cache/apk \
+    set -ex \
+    && apk add \
+    nano
 
 # Make sure that S6 is not so hard on our service startup/shutdown
 ENV \
diff --git a/timescaledb/rootfs/etc/s6-overlay/s6-rc.d/init-addon/run b/timescaledb/rootfs/etc/s6-overlay/s6-rc.d/init-addon/run
--- a/timescaledb/rootfs/etc/s6-overlay/s6-rc.d/init-addon/run
+++ b/timescaledb/rootfs/etc/s6-overlay/s6-rc.d/init-addon/run
@@ -63,9 +63,9 @@ upgradeTimeScaleExtension () {
 			# See: https://github.com/timescale/timescaledb-extras/issues/34
 			# Please note that we do not drop the extension itself, because that would drop the hypertables as well.
 			# The views and functions could be recreated from: https://github.com/timescale/timescaledb-extras
-			psql -U "postgres" homeassistant -c "drop function if exists public.get_dimension_details(regclass)"; \
-			psql -U "postgres" homeassistant -c "drop view if exists public.chunks_tstz"; \
-			psql -U "postgres" homeassistant -c "drop view if exists public.chunks_ts"; \
+			#psql -U "postgres" homeassistant -c "drop function if exists public.get_dimension_details(regclass)"; \
+			#psql -U "postgres" homeassistant -c "drop view if exists public.chunks_tstz"; \
+			#psql -U "postgres" homeassistant -c "drop view if exists public.chunks_ts"; \
 			(psql -X -U postgres -d ${datname} -c "ALTER EXTENSION timescaledb UPDATE;" || true)
 		)
 	done
@@ -175,14 +175,21 @@ else
 	# Check if we need to upgrade from 12 to 15
 	if [[ $(< ${postgres_data}/PG_VERSION) == "12" ]]; then
 		bashio::log.notice "A database upgrade is required from Postgres 12."
-		bashio::log.error "Upgrade was not succesful. This addon version does no longer support Postgres 12. Please upgrade to the previous version of the addon and upgrade to Postgres 14 first." 
+		bashio::log.error "Upgrade was not succesfull. This addon version does no longer support Postgres 12. Please upgrade to the previous version of the addon and upgrade to Postgres 14 first." 
 		exit 1
 	fi
 
 	# Check if we need to upgrade from 14 to 15
 	if [[ $(< ${postgres_data}/PG_VERSION) == "14" ]]; then
 		bashio::log.notice "A database upgrade is required from Postgres 14."
-		if upgradePostgreSQL 14 15; then
+		bashio::log.error "Upgrade was not succesfull. This addon version does no longer support Postgres 12. Please upgrade to the previous version of the addon and upgrade to Postgres 14 first." 
+		exit 1
+	fi
+
+	# Check if we need to upgrade from 15 to 16
+	if [[ $(< ${postgres_data}/PG_VERSION) == "15" ]]; then
+		bashio::log.notice "A database upgrade is required from Postgres 15."
+		if upgradePostgreSQL 15 16; then
 			bashio::log.notice "Upgrade was succesful"
 		else
 			bashio::log.error "Upgrade was not succesful."
